import React from 'react';
import { motion } from 'framer-motion';

const Terms = () => {
  return (
    <div className="min-h-screen bg-base py-32 px-4 md:px-24">
      <div className="max-w-[800px] mx-auto">
        
        {/* Header Block */}
        <div className="mb-24 flex flex-col gap-6">
          <div className="flex items-center gap-4">
            <div className="status-dot" />
            <span className="text-[10px] font-black tracking-[0.5em] text-white/20">SYSTEM_LEGAL_MANIFEST</span>
          </div>
          <h1 className="text-display leading-none">TERMS_&_CONDITIONS</h1>
          <p className="text-sm text-cyber-cyan font-bold tracking-widest uppercase mt-4">VERSION_11.A // LAST_MODIFIED: APRIL_2026</p>
        </div>

        {/* Content manifest */}
        <div className="space-y-24">
          
          <section className="flex flex-col gap-8">
            <div className="flex items-center gap-8">
              <span className="text-2xl font-black text-white/10">01</span>
              <h2 className="text-xl font-black uppercase tracking-tight">System Initialization & Use</h2>
            </div>
            <div className="pl-12 space-y-6 text-sm text-white/40 leading-relaxed font-medium">
              <p>
                By initializing the VitaScan Sentinel System (hereafter "the System"), the Operator (hereafter "User") acknowledges that they are entering a high-fidelity diagnostic environment. Access is granted under strict adherence to the Lumina-Cyber protocol.
              </p>
              <p>
                Unauthorized extraction of neural data, dermal mappings, or acoustic signatures from this platform is strictly prohibited under the Digital Manifest Act.
              </p>
            </div>
          </section>

          <section className="flex flex-col gap-8">
            <div className="flex items-center gap-8">
              <span className="text-2xl font-black text-white/10">02</span>
              <h2 className="text-xl font-black uppercase tracking-tight">Diagnostic Disclaimer</h2>
            </div>
            <div className="pl-12 space-y-6 text-sm text-white/40 leading-relaxed font-medium">
              <p className="text-white/60">
                IMPORTANT: VITASCAN IS A SUPPLEMENTAL PRO-PROTOCOL TOOL. IT DOES NOT SUBSTITUTE PROFESSIONAL BIOMETRIC CONSULTATION.
              </p>
              <p>
                All "Risk Streams," "Pallor Checks," and "Equilibrium Scores" generated by the System are telemetric estimations. The System operates on a probabilistic neural network model (Manifest V11.A) and should be used for monitoring trends, not binary clinical diagnosis.
              </p>
            </div>
          </section>

          <section className="flex flex-col gap-8">
            <div className="flex items-center gap-8">
              <span className="text-2xl font-black text-white/10">03</span>
              <h2 className="text-xl font-black uppercase tracking-tight">Data Sovereignty</h2>
            </div>
            <div className="pl-12 space-y-6 text-sm text-white/40 leading-relaxed font-medium">
              <p>
                All biometric data processed remains within the Sentinel local cache until the Operator triggers a deliberate cloud-uplink. Lumina Design principles ensure that data privacy is not just a policy, but a built-in architectural manifest.
              </p>
            </div>
          </section>

          <section className="flex flex-col gap-8 border-t border-white/5 pt-12">
            <div className="flex items-center justify-between">
              <div className="barcode-sim opacity-20" />
              <div className="flex items-center gap-4">
                 <button className="px-8 py-4 bg-white text-black text-[10px] font-black uppercase tracking-widest cursor-none clickable hover:bg-cyber-cyan transition-all">ACCEPT_MANIFEST</button>
                 <button className="px-8 py-4 bg-transparent border border-white/10 text-white/20 text-[10px] font-black uppercase tracking-widest cursor-none clickable">DOWNLOAD_PDF</button>
              </div>
            </div>
          </section>

        </div>
      </div>
      
      {/* Decorative vertical line */}
      <div className="fixed top-0 left-12 w-[1px] h-full bg-white/5 hidden md:block" />
    </div>
  );
};

export default Terms;
